FROM creatordev/system-test-base

# packages needed for contiki
USER root
RUN apt-get update -yq && apt-get install -yq \
        net-tools \
        iptables \
        tayga \
        libxml2-dev \
        libxslt-dev

ENV SOURCES $HOME

# install Awa and Test Framework dependencies first, before copying main source, to avoid cache invalidation:
ADD creator-system-test-framework/requirements.txt $SOURCES/creator-system-test-framework/requirements.txt
USER user
RUN pip install Mercurial
RUN pip install -r $SOURCES/creator-system-test-framework/requirements.txt

# copy in Test framework and Awa sources
USER root
COPY creator-system-test-framework $SOURCES/creator-system-test-framework
RUN chown user:user -R $SOURCES/creator-system-test-framework

# build AwaLWM2M
WORKDIR $SOURCES/creator-system-test-framework/AwaLWM2M
USER root
RUN make install CMAKE_OPTIONS="-DBUILD_TESTS=OFF"

# TODO support testing arbitrary directory:
#RUN make install CMAKE_OPTIONS="-DBUILD_TESTS=OFF" DESTDIR=/awa

# build Awa contiki application
WORKDIR $SOURCES/creator-system-test-framework/lwm2m-contiki/lwm2m-client-contiki-test
RUN make TARGET=minimal-net
RUN mkdir -p /var/db

# start containers in SOURCES/creator-system-test-framework by default
WORKDIR $SOURCES/creator-system-test-framework

