FROM flowm2m/test-base

# copy in Awa contiki application
USER root
COPY DeviceManagementTests/lwm2m-contiki $HOME/DeviceManagementTests/lwm2m-contiki
RUN chown user:user -R $HOME/DeviceManagementTests/lwm2m-contiki

# build Awa contiki application
USER user
RUN cd DeviceManagementTests/lwm2m-contiki/lwm2m-client-contiki-test && make TARGET=minimal-net

# packages needed for contiki
USER root
RUN apt-get update -yq && apt-get install -yq \
        net-tools \
        iptables \
        tayga

# copy binaries and scripts to /awa
USER root
RUN mkdir -p /awa/bin
RUN cp DeviceManagementTests/lwm2m-contiki/lwm2m-client-contiki-test/lwm2m-client-contiki-test.minimal-net /awa/bin
RUN cp -r DeviceManagementTests/lwm2m-contiki/scripts /awa

