FROM registry-hh.flowcloud.systems:5000/flowm2m/system-test-base

# packages needed for contiki
USER root
RUN apt-get update -yq && apt-get install -yq \
        net-tools \
        iptables \
        tayga \
        libxml2-dev \
        libxslt-dev

ENV SOURCES $HOME

# install Awa and Test Framework dependencies first, before copying main source, to avoid cache invalidation:
ADD requirements.txt $SOURCES/DeviceManagementTests/requirements.txt
USER user
RUN pip install Mercurial
RUN pip install -r $SOURCES/DeviceManagementTests/requirements.txt

# copy in Test framework and Awa sources
USER root
RUN mkdir -p $SOURCES/DeviceManagementTests
COPY ./* $SOURCES/DeviceManagementTests/
RUN chown user:user -R $SOURCES/DeviceManagementTests

# build AwaLWM2M
WORKDIR $SOURCES/DeviceManagementTests/AwaLWM2M
USER root
RUN make install CMAKE_OPTIONS="-DBUILD_TESTS=OFF"

# TODO support testing arbitrary directory:
#RUN make install CMAKE_OPTIONS="-DBUILD_TESTS=OFF" DESTDIR=/awa

# build Awa contiki application
WORKDIR $SOURCES/DeviceManagementTests/lwm2m-contiki/lwm2m-client-contiki-test
#RUN make TARGET=minimal-net
#RUN mkdir -p /var/db

# start containers in SOURCES/DeviceManagementTests by default
#WORKDIR $SOURCES/DeviceManagementTests

