FROM ubuntu:15.10
ENV DEBIAN_FRONTEND noninteractive

# install package dependencies
RUN apt-get update -yq && apt-get install -yq \
	apt-utils \
	git \
	curl \
	make \
	automake \
	build-essential \
	libssl-dev \
	zlib1g-dev \
	libbz2-dev \
	libreadline-dev \
	libsqlite3-dev \
	libncurses5-dev \
	libncursesw5-dev \
	cmake
# apt-get clean is automatic for Ubuntu images

# create a user to run as
RUN useradd -m user
WORKDIR /home/user
ENV HOME /home/user
USER user

# install pyenv
RUN git clone https://github.com/yyuu/pyenv.git .pyenv
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

# install python 2.7.11 within pyenv
RUN pyenv install 2.7.11 && pyenv global 2.7.11 && pyenv rehash

