FROM test-env

# copy in Awa contiki application
USER root
COPY creator-system-test-framework/lwm2m-contiki $HOME/creator-system-test-framework/lwm2m-contiki
RUN chown user:user -R $HOME/creator-system-test-framework/lwm2m-contiki

# build Awa contiki application
USER user
WORKDIR $HOME

ARG TINYDTLS
ENV TINYDTLS ${TINYDTLS}
RUN make -C creator-system-test-framework/lwm2m-contiki/lwm2m-client-contiki-test TARGET=minimal-net clean all

# packages needed for contiki
USER root
RUN apt-get update -yq && apt-get install -yq \
        net-tools \
        iptables \
        tayga

# copy binaries and scripts to /awa
USER root
RUN mkdir -p /awa/bin
RUN cp creator-system-test-framework/lwm2m-contiki/lwm2m-client-contiki-test/lwm2m-client-contiki-test.minimal-net /awa/bin
RUN cp -r creator-system-test-framework/lwm2m-contiki/scripts /awa

