paths:
  libawa: ../AwaLWM2M/build/api/src/libawa.so
  awa-clientd: ../AwaLWM2M/build/core/src/client/awa_clientd
  awa-serverd: ../AwaLWM2M/build/core/src/server/awa_serverd
  awa-bootstrapd: ../AwaLWM2M/build/core/src/bootstrap/awa_bootstrapd
  constrained-client: ../lwm2m-contiki/lwm2m-client-contiki-test/lwm2m-client-contiki-test.minimal-net
  tayga-scripts: ../lwm2m-contiki/scripts

topologies:
  local-gateways:
    # Gateway client/server interaction - No provisioning
    bootstrap-servers: local
    gateway-servers: local
    gateway-clients: local

bootstrap-servers:
  local:
    config: bootstrap-configs/bootstrap-localhost.config
    ip-address: 127.0.0.1
#    interface: null
#    address-family: null
    port: 15685
    log: gwbootstrapd.log
    proxy: local-bootstrap-server
  contiki:
    config: bootstrap-configs/bootstrap-contiki.config
    config2: bootstrap-configs/bootstrap-contiki-flow-NAT64.config
    ip-address: 127.0.0.1
    port: 15683
    log: gwbootstrapd.log
    proxy: local-bootstrap-server
    address-family: 6
    interface: tap0

gateway-servers:
  local:
    ip-address: 127.0.0.2
    port: 5683
    ipc-address: 127.0.0.2
    ipc-port: 54321
#    interface: null
#    address-family: null
    log: gateway_server_local.log
    content-type: 1542
    proxy: local-gateway-server
  contiki:
    ip-address: 127.0.0.2
    port: 5683
    ipc-address: 127.0.0.2
    ipc-port: 54321
    interface: tap0
    address-family: 6
    log: gateway_server_local.log
    content-type: 1542
    proxy: local-gateway-server

gateway-clients:
  local:
    client-id: test_local_client
    device-name: TestGatewayDevice1
    port: 6000
    address-family: 4
    ipc-address: 127.0.0.1
    ipc-port: 12345
    log: gateway_client_local.log
    bootstrap-uri: coap://127.0.0.1:15685
    proxy: local-gateway-client

constrained-clients:
  local:
    client-id: constrained1
    device-name: TestConstrainedDevice1
    serial-number: SN12345678CD
    bootstrap-uri: coap://[2001:1418:100::1]:15683
    port: 6007
    proxy: local-constrained-client
    tayga:
      ip-address: aaaa::1
      ethif: eth0

proxies:
  local-bootstrap-server:
    protocol: XMLRPC
    ip-address: 127.0.0.1
    port: 4442
  local-gateway-server:
    protocol: XMLRPC
    ip-address: 127.0.0.1
    port: 4342
  local-gateway-client:
    protocol: XMLRPC
    ip-address: 127.0.0.1
    port: 4242
  local-constrained-client:
    protocol: XMLRPC
    ip-address: 127.0.0.1
    port: 4142

